### ISSUE TITLE
Token Auth JWT_PUBLIC_KEY on Mothership

### ISSUE THREAD

**Issue by yusufRahmatullah** [bukalapak/envsync#15]
`env.sample` in Mothership, the `JWT_PUBLIC_KEY` surrounded by double-quotes (`"`) and using `\n` for the new line (based on [this stackoverflow answer](https://stackoverflow.com/a/43380839)).
But, envsync remove the double-quotes and the newline.

**Comment by h4ckm03d** [comment]
Noted, I think need save raw value before rewrite to new env. Thanks
